name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile cover.out ./...

    - name: Generate coverage report
      run: go tool cover -html=cover.out -o coverage.html

    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: ./coverage.html

    - name: Check formatting
      run: gofmt -s -l $(go list -f {{.Dir}} ./...)
      continue-on-error: true

    - name: Check old APIs
      run: go tool fix -diff $(go list -f {{.Dir}} ./...)
      continue-on-error: true
